name = "rabbit-server-list"
main = "src/index.js"
compatibility_date = "2023-03-21"

[[kv_namespaces]]
binding = "KV"
id = "8f6ee5b816384dc4a5736660603e0325"

[[d1_databases]]
binding = "DB"
database_name = "rabbit-server-list"
database_id = "1167ecc9-c3e5-41c8-ae72-5e10c653cc40"

[[r2_buckets]]
binding = 'R2'
bucket_name = 'rabbitserverlist'

[[analytics_engine_datasets]]
binding = "MAE"
dataset = "rabbit-server-list-minecraft"

[vars]
ACCOUNT_ID = "eb996327383b1ba7869926dcb856b4ae"

# Don't forget to add CRAWLER_SECRET_TOKEN with: wrangler secret put CRAWLER_SECRET_TOKEN
# Don't forget to set the secret Cloudflare token with: wrangler secret put CF_TOKEN
# Don't forget to set the secret Cloudflare token with: wrangler secret put CF_TURNSTILE_TOKEN